language: python
python:
- 3.6
deploy:
  provider: pypi
  user: Mryan
  password:
    secure: LxadlM6dkrGxf59n0nVtVXLXoq8K8HKFhHn4pF2Nu7h88mjErGE9dakH310qJNEvuf/f30b+s70RcmijSEPNeHAgwto4IkP5YN3Wfnr1LcrHTmAfjbJo73KuFfXc+XJOfSE3vU+uwg8Nyz9+iOxUs3z67XWp4K16eDOr1Jycm4G+IT7p3O8DfsKeOISeBN120Q4fsTfLmejdouDLe4jYzG9mLJGHBYXr39m7IQjGxiac0EmvcTT5o4L+M0XZK0Z/hh7JAvgVGZyUG04TJgPkybBliH22VfIckhCxlTWlcLxvSCX0J9LvllYsq+boiTvUsDvu4GnHdQI0LdI9l+HkwHA1xRxQuBmIYO7natTMyxDrskpFs0EQ9qj0ypmF0si9kZNUbrHQuLsd1CXzJFkDiWpofmstLzLpOMWu/SGLn2/KnhO9WdibD/AOIlTVFupBkfUiCI8+5k0MjwbC5PMKCsgjAIoSrjr7Lxoc3b97BsY9fn3f+7br5rpabob9iS4FM6OyDvsGM3XTP3TDt4Wp+LtlNcljRPQc7x05X6sFco/UGont9U1cemIzr/rJ1OToK/bAKSE7oKHQQwq99SgkfnLwiL6OdbOsvLl0+oOwse4+jQ9FMV4U941qo7AIT3IyyMFLlDexh9yYP3rfoNUKD7MGCSZtIRfV1QU5PWNt58Q=
